//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.DataContracts
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CreateEmployeeRequest", Namespace = "http://schemas.datacontract.org/2004/07/EmployeeManagement.DataContracts")]
    public partial class CreateEmployeeRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private EmployeeManagement.DataContracts.Employee EmployeeField;

        private string TeamField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmployeeManagement.DataContracts.Employee Employee
        {
            get
            {
                return this.EmployeeField;
            }
            set
            {
                this.EmployeeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Team
        {
            get
            {
                return this.TeamField;
            }
            set
            {
                this.TeamField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Employee", Namespace = "http://schemas.datacontract.org/2004/07/EmployeeManagement.DataContracts")]
    public partial class Employee : EmployeeManagement.DataContracts.Person
    {

        private EmployeeManagement.DataContracts.Gender GenderField;

        private int IdField;

        private EmployeeManagement.DataContracts.Name NameField;

        private EmployeeManagement.DataContracts.Remark[] RemarkField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmployeeManagement.DataContracts.Gender Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmployeeManagement.DataContracts.Name Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmployeeManagement.DataContracts.Remark[] Remark
        {
            get
            {
                return this.RemarkField;
            }
            set
            {
                this.RemarkField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Person", Namespace = "http://schemas.datacontract.org/2004/07/EmployeeManagement.DataContracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EmployeeManagement.DataContracts.Employee))]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int PanCardIdField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PanCardId
        {
            get
            {
                return this.PanCardIdField;
            }
            set
            {
                this.PanCardIdField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Name", Namespace = "http://schemas.datacontract.org/2004/07/EmployeeManagement.DataContracts")]
    public partial class Name : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string FirstNameField;

        private string LastNameField;

        private string MiddleNameField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName
        {
            get
            {
                return this.MiddleNameField;
            }
            set
            {
                this.MiddleNameField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Gender", Namespace = "http://schemas.datacontract.org/2004/07/EmployeeManagement.DataContracts")]
    public enum Gender : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Male = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Female = 1,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Remark", Namespace = "http://schemas.datacontract.org/2004/07/EmployeeManagement.DataContracts")]
    public partial class Remark : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.DateTime DateTimeField;

        private string TextField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime
        {
            get
            {
                return this.DateTimeField;
            }
            set
            {
                this.DateTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AddRemarkRequest", Namespace = "http://schemas.datacontract.org/2004/07/EmployeeManagement.DataContracts")]
    public partial class AddRemarkRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdField;

        private EmployeeManagement.DataContracts.Remark RemarkField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmployeeManagement.DataContracts.Remark Remark
        {
            get
            {
                return this.RemarkField;
            }
            set
            {
                this.RemarkField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DefaultFault", Namespace = "http://schemas.datacontract.org/2004/07/EmployeeManagement.DataContracts")]
    public partial class DefaultFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string Error1Field;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error1
        {
            get
            {
                return this.Error1Field;
            }
            set
            {
                this.Error1Field = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "ICreateEmployee")]
public interface ICreateEmployee
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICreateEmployee/CreateEmployee", ReplyAction = "http://tempuri.org/ICreateEmployee/CreateEmployeeResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(EmployeeManagement.DataContracts.DefaultFault), Action = "http://tempuri.org/ICreateEmployee/CreateEmployeeDefaultFaultFault", Name = "DefaultFault", Namespace = "http://schemas.datacontract.org/2004/07/EmployeeManagement.DataContracts")]
    EmployeeManagement.DataContracts.Employee CreateEmployee(EmployeeManagement.DataContracts.CreateEmployeeRequest employee);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICreateEmployee/CreateEmployee", ReplyAction = "http://tempuri.org/ICreateEmployee/CreateEmployeeResponse")]
    System.Threading.Tasks.Task<EmployeeManagement.DataContracts.Employee> CreateEmployeeAsync(EmployeeManagement.DataContracts.CreateEmployeeRequest employee);

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/ICreateEmployee/AddRemark")]
    void AddRemark(EmployeeManagement.DataContracts.AddRemarkRequest remark);

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/ICreateEmployee/AddRemark")]
    System.Threading.Tasks.Task AddRemarkAsync(EmployeeManagement.DataContracts.AddRemarkRequest remark);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICreateEmployeeChannel : ICreateEmployee, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CreateEmployeeClient : System.ServiceModel.ClientBase<ICreateEmployee>, ICreateEmployee
{

    public CreateEmployeeClient()
    {
    }

    public CreateEmployeeClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public CreateEmployeeClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public CreateEmployeeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public CreateEmployeeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    public EmployeeManagement.DataContracts.Employee CreateEmployee(EmployeeManagement.DataContracts.CreateEmployeeRequest employee)
    {
        return base.Channel.CreateEmployee(employee);
    }

    public System.Threading.Tasks.Task<EmployeeManagement.DataContracts.Employee> CreateEmployeeAsync(EmployeeManagement.DataContracts.CreateEmployeeRequest employee)
    {
        return base.Channel.CreateEmployeeAsync(employee);
    }

    public void AddRemark(EmployeeManagement.DataContracts.AddRemarkRequest remark)
    {
        base.Channel.AddRemark(remark);
    }

    public System.Threading.Tasks.Task AddRemarkAsync(EmployeeManagement.DataContracts.AddRemarkRequest remark)
    {
        return base.Channel.AddRemarkAsync(remark);
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IReturnEmployees")]
public interface IReturnEmployees
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReturnEmployees/ReturnEmployee", ReplyAction = "http://tempuri.org/IReturnEmployees/ReturnEmployeeResponse")]
    EmployeeManagement.DataContracts.Employee ReturnEmployee(int id);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReturnEmployees/ReturnEmployee", ReplyAction = "http://tempuri.org/IReturnEmployees/ReturnEmployeeResponse")]
    System.Threading.Tasks.Task<EmployeeManagement.DataContracts.Employee> ReturnEmployeeAsync(int id);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReturnEmployees/ReturnEmployeeList", ReplyAction = "http://tempuri.org/IReturnEmployees/ReturnEmployeeListResponse")]
    EmployeeManagement.DataContracts.Employee[] ReturnEmployeeList();

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReturnEmployees/ReturnEmployeeList", ReplyAction = "http://tempuri.org/IReturnEmployees/ReturnEmployeeListResponse")]
    System.Threading.Tasks.Task<EmployeeManagement.DataContracts.Employee[]> ReturnEmployeeListAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IReturnEmployeesChannel : IReturnEmployees, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ReturnEmployeesClient : System.ServiceModel.ClientBase<IReturnEmployees>, IReturnEmployees
{

    public ReturnEmployeesClient()
    {
    }

    public ReturnEmployeesClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public ReturnEmployeesClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public ReturnEmployeesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public ReturnEmployeesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    public EmployeeManagement.DataContracts.Employee ReturnEmployee(int id)
    {
        return base.Channel.ReturnEmployee(id);
    }

    public System.Threading.Tasks.Task<EmployeeManagement.DataContracts.Employee> ReturnEmployeeAsync(int id)
    {
        return base.Channel.ReturnEmployeeAsync(id);
    }

    public EmployeeManagement.DataContracts.Employee[] ReturnEmployeeList()
    {
        return base.Channel.ReturnEmployeeList();
    }

    public System.Threading.Tasks.Task<EmployeeManagement.DataContracts.Employee[]> ReturnEmployeeListAsync()
    {
        return base.Channel.ReturnEmployeeListAsync();
    }
}
